### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by chain-ed-reaction** [spaciecat/cells#1]
Hello,
Your work on elementary cellular automata was really cool. I am still getting started with java to build interactive games to aid my learning.
Just curious can I reuse your code on revealjs slides I am having on my mind. Its on an introduction to agent based modelling. So do you mind specifying the license for your work?

**Comment by spaciecat** [comment]
The bottom of the hosted page says MIT license, but I've added the license file to the repository as well.
You're free to use my code to do whatever you want! Have fun with it 😸
